In [26]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [45]:
path = "flight_data/"

nodes_col_Names = ['Airport_ID', 'Name', 'City', 'Country', 'IATA', 'ICAO', 'Latitude', 'Longitude', 'Altitude', 'Timezone', 'DST', 'Tz_database_time_zone', 'Type', 'Source']
edges_col_Names = ['Airline', 'Airline_ID', 'Source_Airport', 'Source_Airport_ID', 'Destination_Airport', 'Destination_Airport_ID', 'Codeshare', 'Stops', 'Equipment']

nodes_df = pd.read_csv(path+'/airports.dat', names = nodes_col_Names)
edges_df = pd.read_csv(path+'/routes.dat', names = edges_col_Names)

nodes_df.shape

(7184, 14)

In [46]:
c_1 = pd.read_csv('data/Countries-Continents.csv')
c_1.loc[len(c_1)]=['Asia','Russia'] 
c_1.loc[len(c_1)]=['North America','United States'] 
c_1.loc[len(c_1)]=['Africa','Cote d\'Ivoire'] 
c_1.loc[len(c_1)]=['Africa','Congo (Kinshasa)'] 
c_1.loc[len(c_1)]=['Asia','South Korea'] 
c_1.loc[len(c_1)]=['Asia','Burma'] 
c_1.loc[len(c_1)]=['Europe','Czech Republic'] 
c_1.loc[len(c_1)]=['Asia','North Korea'] 
c_1.loc[len(c_1)]=['Antarctica','Antarctica'] 
c_1.loc[len(c_1)]=['Antarctica','Antarctica'] 
c_1.loc[len(c_1)]=['Asia','Taiwan'] 
c_1.loc[len(c_1)]=['Africa','Congo (Brazzaville)'] 
c_1.loc[len(c_1)]=['Africa','Reunion'] 
c_1.loc[len(c_1)]=['Asia','West Bank'] 
c_1.loc[len(c_1)]=['Asia','Taiwan'] 
c_1.loc[len(c_1)]=['North America','Greenland'] 
c_1.loc[len(c_1)]=['Africa','Burkina Faso'] 
c_1.loc[len(c_1)]=['Europe','Guernsey'] 
c_1.loc[len(c_1)]=['Europe','Jersey']
c_1.loc[len(c_1)]=['Europe','Isle of Man']
c_1.loc[len(c_1)]=['Europe','Isle Of Man']
c_1.loc[len(c_1)]=['South America','Falkland Islands'] 
c_1.loc[len(c_1)]=['Africa','Dzaoudzi'] 
c_1.loc[len(c_1)]=['North America','Saint Pierre and Miquelon'] 
c_1.loc[len(c_1)]=['Europe','Gibraltar']
c_1.loc[len(c_1)]=['South America','British Virgin Islands']
c_1.loc[len(c_1)]=['Oceania','Faroe Islands']
c_1.loc[len(c_1)]=['Oceania','French Polynesia']
c_1.loc[len(c_1)]=['South America','Puerto Rico']
c_1.loc[len(c_1)]=['South America','Guadeloupe']
c_1.loc[len(c_1)]=['Oceania','New Caledonia']
c_1.loc[len(c_1)]=['Oceania','Cocos (Keeling) Islands']
c_1.loc[len(c_1)]=['South America','Turks and Caicos Islands']
c_1.loc[len(c_1)]=['Oceania','Cook Islands']
c_1.loc[len(c_1)]=['Europe','Svalbard']
c_1.loc[len(c_1)]=['South America','American Samoa']
c_1.loc[len(c_1)]=['South America','French Guiana']
c_1.loc[len(c_1)]=['Asia','Guam']
c_1.loc[len(c_1)]=['Asia','Northern Mariana Islands']
c_1.loc[len(c_1)]=['South America','Virgin Islands']
c_1.loc[len(c_1)]=['Europe','Netherlands Antilles']
c_1.loc[len(c_1)]=['Asia','Hong Kong']
c_1.loc[len(c_1)]=['Oceania','Christmas Island']
c_1.loc[len(c_1)]=['North America','Bermuda']
c_1.loc[len(c_1)]=['Africa','Western Sahara']
c_1.loc[len(c_1)]=['North America','Cayman Islands']


nodes_df = nodes_df.merge(c_1, on='Country', how="left")
nodes_df.sort_values(by="Altitude", ascending=False)
nodes_df.shape

(7215, 15)

In [47]:
# show airports without continent
nodes_df[nodes_df['Continent'].isnull()]

,Airport_ID,Name,City,Country,IATA,ICAO,Latitude,Longitude,Altitude,Timezone,DST,Tz_database_time_zone,Type,Source,Continent
872,892,RAF Ascension Island,Wide Awake,Saint Helena,ASI,FHAW,-7.969600,-14.393700,278,0,N,Atlantic/St_Helena,airport,OurAirports,NaN
875,895,Diego Garcia Naval Support Facility,Diego Garcia Island,British Indian Ocean Territory,\N,FJDG,-7.313270,72.411102,9,6,U,Indian/Chagos,airport,OurAirports,NaN
895,915,Dzaoudzi Pamandzi International Airport,Dzaoudzi,Mayotte,DZA,FMCZ,-12.804700,45.281101,23,3,U,Indian/Mayotte,airport,OurAirports,NaN
1900,1968,Hihifo Airport,Wallis,Wallis and Futuna,WLS,NLWW,-13.238300,-176.199005,79,12,U,Pacific/Wallis,airport,OurAirports,NaN
2159,2253,Henderson Field,Midway,Midway Islands,MDY,PMDY,28.201700,-177.380997,13,-11,U,Pacific/Midway,airport,OurAirports,NaN
2754,2878,Martinique Aimé Césaire International Airport,Fort-de-france,Martinique,FDF,TFFF,14.591000,-61.003201,16,-4,U,America/Martinique,airport,OurAirports,NaN
2769,2895,Queen Beatrix International Airport,Oranjestad,Aruba,AUA,TNCA,12.501400,-70.015198,60,-4,U,America/Aruba,airport,OurAirports,NaN
2774,2900,Wallblake Airport,The Valley,Anguilla,AXA,TQPF,18.204800,-63.055099,127,-4,U,America/Anguilla,airport,OurAirports,NaN
2970,3121,Macau International Airport,Macau,Macau,MFM,VMMC,22.149599,113.592003,20,8,U,Asia/Macau,airport,OurAirports,NaN
3175,3359,Norfolk Island International Airport,Norfolk Island,Norfolk Island,NLK,YSNF,-29.041599,167.938995,371,11,U,Pacific/Norfolk,airport,OurAirports,NaN
3763,3969,Yasser Arafat International Airport,Gaza,Palestine,GZA,LVGZ,31.246401,34.276100,320,2,U,Asia/Gaza,airport,OurAirports,NaN
3918,4146,John A. Osborne Airport,Geralds,Montserrat,MNI,TRPG,16.791401,-62.193298,550,-4,N,America/Montserrat,airport,OurAirports,NaN
4106,4382,Johnston Atoll Airport,Johnston Island,Johnston Atoll,JON,PJON,16.728600,-169.533997,7,-10,U,Pacific/Johnston,airport,OurAirports,NaN
4548,5884,Niue International Airport,Alofi,Niue,IUE,NIUE,-19.079031,-169.925598,209,-11,U,Pacific/Niue,airport,OurAirports,NaN
4549,5885,Pointe Vele Airport,Futuna Island,Wallis and Futuna,FUT,NLWF,-14.311400,-178.065994,20,12,U,Pacific/Wallis,airport,OurAirports,NaN
5164,6787,Kalay Airport,Kalemyo,Myanmar,KMV,VYKL,23.188801,94.051102,499,6.5,U,Asia/Rangoon,airport,OurAirports,NaN
5717,7674,Wake Island Airfield,Wake island,Wake Island,AWK,PWAK,19.282101,166.636002,14,-10,U,Pacific/Johnston,airport,OurAirports,NaN

In [30]:
nodes_df["Continent"].value_counts()

North America    2151
Asia             1618
Europe           1471
Africa            707
South America     690
Oceania           547
Antarctica         14
Name: Continent, dtype: int64

In [48]:
# search for continent
#nodes_df[nodes_df["Continent"] == "Antarctica"]

In [32]:
nodes_df["Continent"].unique()

array(['Oceania', 'North America', 'Europe', 'Africa', 'South America',
       nan, 'Asia', 'Antarctica'], dtype=object)

In [87]:
nodes_df_export = nodes_df[['Latitude','Longitude','Country','Continent','Airport_ID','IATA']]
nodes_df_export = nodes_df_export.set_index('Airport_ID')
nodes_df_export.columns = [ 'lat', 'lon', 'country', 'continent', 'IATA']
nodes_df_export.to_csv('../data/airports.csv')
nodes_df_export.head()

                 lat         lon           country continent IATA
Airport_ID
1          -6.081690  145.391998  Papua New Guinea   Oceania  GKA
2          -5.207080  145.789001  Papua New Guinea   Oceania  MAG
3          -5.826790  144.296005  Papua New Guinea   Oceania  HGU
4          -6.569803  146.725977  Papua New Guinea   Oceania  LAE
5          -9.443380  147.220001  Papua New Guinea   Oceania  POM

In [88]:
_dict = nodes_df_export.to_dict(orient='records')
_dict[1]

{'lat': -5.20707988739,
 'lon': 145.789001465,
 'country': 'Papua New Guinea',
 'continent': 'Oceania',
 'IATA': 'MAG'}

In [89]:
load = pd.read_csv('./web_data/airports.csv')
load

      Airport_ID        lat         lon           country      continent IATA
0              1  -6.081690  145.391998  Papua New Guinea        Oceania  GKA
1              2  -5.207080  145.789001  Papua New Guinea        Oceania  MAG
2              3  -5.826790  144.296005  Papua New Guinea        Oceania  HGU
3              4  -6.569803  146.725977  Papua New Guinea        Oceania  LAE
4              5  -9.443380  147.220001  Papua New Guinea        Oceania  POM
5              6  -3.583830  143.669006  Papua New Guinea        Oceania  WWK
6              7  61.160500  -45.425999         Greenland  North America  UAK
7              8  64.190903  -51.678101         Greenland  North America  GOH
8              9  67.012222  -50.711603         Greenland  North America  SFJ
9             10  76.531197  -68.703201         Greenland  North America  THU
10            11  65.660004  -18.072701           Iceland         Europe  AEY
11            12  65.283302  -14.401400           Iceland         Europe  EGS
12            13  64.295601  -15.227200           Iceland         Europe  HFN
13            14  65.952301  -17.426001           Iceland         Europe  HZK
14            15  66.058098  -23.135300           Iceland         Europe  IFJ
15            16  63.985001  -22.605600           Iceland         Europe  KEF
16            17  65.555801  -23.965000           Iceland         Europe  PFJ
17            18  64.129997  -21.940599           Iceland         Europe  RKV
18            19  66.133301  -18.916700           Iceland         Europe  SIJ
19            20  63.424301  -20.278900           Iceland         Europe  VEY
20            21  46.485001  -84.509399            Canada  North America  YAM
21            22  50.056400  -97.032501            Canada  North America  YAV
22            23  44.639702  -63.499401            Canada  North America  YAW
23            24  51.391899  -56.083099            Canada  North America  YAY
24            25  49.079833 -125.775583            Canada  North America  YAZ
25            26  68.534401  -89.808098            Canada  North America  YBB
26            27  49.132500  -68.204399            Canada  North America  YBC
27            28  48.330601  -70.996399            Canada  North America  YBG
28            29  64.298897  -96.077797            Canada  North America  YBK
29            30  49.950802 -125.271004            Canada  North America  YBL
...          ...        ...         ...               ...            ...  ...
7185       12028 -35.751400  143.938995         Australia        Oceania  KRA
7186       12029 -31.074400  152.770004         Australia        Oceania  KPS
7187       12030 -26.580799  151.841003         Australia        Oceania  KGY
7188       12031 -38.207199  146.470001         Australia        Oceania  TGN
7189       12032 -17.069201  145.419006         Australia        Oceania  MRG
7190       12033 -14.722800  134.746994         Australia        Oceania  RPM
7191       12034 -32.214699  148.225006         Australia        Oceania  QRM
7192       12035 -33.238899  137.994995         Australia        Oceania  PPI
7193       12036 -40.834999  145.084000         Australia        Oceania  SIO
7194       12037 -11.422800  130.654007         Australia        Oceania  SNB
7195       12038 -37.071701  142.740997         Australia        Oceania  SWC
7196       12039 -29.451099  142.057999         Australia        Oceania  TYB
7197       12040 -35.262798  148.240997         Australia        Oceania  TUM
7198       12041 -36.415798  146.307007         Australia        Oceania  WGT
7199       12042 -36.321098  142.419006         Australia        Oceania  WKB
7200       12043 -31.733299  147.802994         Australia        Oceania  QRR
7201       12044 -38.090827  146.965335         Australia        Oceania  SXE
7202       12045 -33.937199  147.190994         Australia        Oceania  WWY
7203       12046 -34.255600  148.248001         Australia        Oceania  NGA
7204       12047  32.389400  111.695000             China           Asia  LHK
7205       12048  32.591667  110.907778             China           Asia  WDS
7206       12049  39.415699  125.894997       North Korea           Asia   \N
7207       12050  38.201984   90.841495             China           Asia  HTT
7208       12051  46.660301  113.285004          Mongolia           Asia  UUN
7209       12052  32.847733  117.320244             China           Asia  BFU
7210       12053  32.257885  120.501656             China           Asia  RUG
7211       12054  31.390600  118.408997             China           Asia  WHU
7212       12055  42.911701   90.247498             China           Asia  SXJ
7213       12056  40.542524  122.358600             China           Asia  YKH
7214       12057  41.784401  123.496002             China           Asia   \N

[7215 rows x 6 columns]